FinezWebApp452mvc/Models/Branch.cs
using FinezWebApp452mvc.Models.Abstract;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FinezWebApp452mvc.Models
{
    public class Branch:Entity<int>
    {
        [Column("client_id")]
        [ForeignKey("Client")]
        public int ClientId { get; set; }
        [Column("name")]
        [MaxLength(50), Required]
        public string Name { get; set; }
        [Column("branch_code")]
        [MaxLength(50), Required]
        public string BranchCode { get; set; }
        [Column("street")]
        [MaxLength(100), Required]
        public string Street { get; set; }
        [Column("city")]
        [MaxLength(50), Required]
        public string City { get; set; }
        [Column("district")]
        [MaxLength(50), Required]
        public string District { get; set; }
        [Column("state")]
        [MaxLength(50), Required]
        public string State { get; set; }
        [Column("pin_code")]
        [MaxLength(50), Required]
        public string Pincode { get; set; }
        [Column("phone"), DataType(DataType.PhoneNumber), Index(IsUnique = true), MaxLength(50)]
        public string Phone { get; set; }
        [Column("mobile"), Required, DataType(DataType.PhoneNumber), Index(IsUnique = true), MaxLength(50)]
        public string Mobile { get; set; }
        [Column("email"), Required, DataType(DataType.EmailAddress), Index(IsUnique = true), MaxLength(50)]
        public string Email { get; set; }
        [Column("website"),DataType(DataType.Url)]
        public string Website { get; set; }
        [Column("is_main_branch",TypeName ="bit")]
        public bool IsMainBranch { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("expiry_date", TypeName = "datetime2")]
        public DateTime ExpiryDate { get; set; }

        public virtual Client Client { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}

FinezWebApp452mvc/Models/ViewModels/BranchViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FinezWebApp452mvc.Models.ViewModels
{
    public class AddBranchVM
    {
        public int ClientId { get; set; }
        [MaxLength(50), Required]
        public string Name { get; set; }
        [Display(Name = "Street")]
        [MaxLength(100), Required]
        public string Street { get; set; }
        [Display(Name ="City")]
        [MaxLength(50), Required]
        public string City { get; set; }
        [Display(Name = "District")]
        [MaxLength(50), Required]
        public string District { get; set; }
        [Display(Name = "State")]
        [MaxLength(50), Required]
        public string State { get; set; }
        [Display(Name = "Pin code")]
        [MaxLength(50), Required]
        public string Pincode { get; set; }
        [DataType(DataType.PhoneNumber),Phone, MaxLength(50)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string Phone { get; set; }
        [Required, DataType(DataType.PhoneNumber), Phone, MaxLength(50)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string Mobile { get; set; }
        [Required, DataType(DataType.EmailAddress),EmailAddress, MaxLength(50)]
        public string Email { get; set; }
        [ DataType(DataType.Url)]
        public string Website { get; set; }
        [Display(Name = "Expiry date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ExpiryDate { get; set; }
        [Display(Name ="Is main branch")]
        public bool IsMainBranch { get; set; }
        public bool IsSuccess { get; set; } = false;
        public string SuccessMessage { get; set; } = "";

        public AddEmployeeVM EmployeeVM { get; set; }
    }

    public class EditBranchVM
    {
        public int Id { get; set; }
        [MaxLength(50), Required]
        public string Name { get; set; }
        [Display(Name = "Street")]
        [MaxLength(100), Required]
        public string Street { get; set; }
        [Display(Name = "City")]
        [MaxLength(50), Required]
        public string City { get; set; }
        [Display(Name = "District")]
        [MaxLength(50), Required]
        public string District { get; set; }
        [Display(Name = "State")]
        [MaxLength(50), Required]
        public string State { get; set; }
        [Display(Name = "Pin code")]
        [MaxLength(50), Required]
        public string Pincode { get; set; }
        [DataType(DataType.PhoneNumber), Phone, MaxLength(50)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string Phone { get; set; }
        [Required, DataType(DataType.PhoneNumber), Phone, MaxLength(50)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string Mobile { get; set; }
        [Required, DataType(DataType.EmailAddress), EmailAddress, MaxLength(50)]
        public string Email { get; set; }
        [DataType(DataType.Url)]
        public string Website { get; set; }
        [Display(Name = "Expiry date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ExpiryDate { get; set; }
        [Display(Name = "Is main branch")]
        public bool IsMainBranch { get; set; }
        public bool IsSuccess { get; set; } = false;
        public string SuccessMessage { get; set; } = "";
    }

    public class BranchVM
    {
        public int BranchId { get; set; }
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string BranchCode { get; set; }
        public string ClientName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        [DataType(DataType.PhoneNumber),Phone, MaxLength(50)]
        public string Phone { get; set; }
        [Required, DataType(DataType.PhoneNumber),Phone, MaxLength(50)]
        public string Mobile { get; set; }
        [Required, DataType(DataType.EmailAddress),EmailAddress, MaxLength(50)]
        public string Email { get; set; }
        [DataType(DataType.Url)]
        public string Website { get; set; }
        public bool IsMainBranch { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ExpiryDate { get; set; }
        public List<EmployeeVM> Employees { get; set; }

        public BranchStatus Status { get; set; }
    }

    public enum BranchStatus
    {
        InActive = 0,
        Active = 1
    }
}

FinezWebApp452mvc/Controllers/API/BranchController.cs
using FinezWebApp452mvc.Buisiness;
using FinezWebApp452mvc.Controllers.Base;
using FinezWebApp452mvc.Exceptions;
using FinezWebApp452mvc.Models.ViewModels;
using FinezWebApp452mvc.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;

namespace FinezWebApp452mvc.Controllers.API
{
    public class BranchController : BaseAPIController
    {
        BranchManager branchManager;
        AppLogger appLogger;
        public BranchController()
        {
            this.branchManager = new BranchManager(this.dbContext);
            appLogger = new AppLogger("BranchAPIController");
        }

        [Authorize]
        [HttpPut]
        public async Task<IHttpActionResult> RegisterDevice(RegisterDeviceVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await this.branchManager.RegisterDevice(model, HttpContext.Current.GetOwinContext());
                    return Ok();
                }
                else
                {
                    appLogger.write("Register model error", string.Join(",", ModelState.Values.SelectMany(v => v.Errors)));
                    return Content(HttpStatusCode.BadRequest, new FailureResponse() { Message = "Device registration failed", Errors = ModelState.Values.SelectMany(v => v.Errors).Select(y => y.ErrorMessage).ToList() });
                }
                
            }
            catch (FailureResponseException e)
            {
                appLogger.write(e);
                return Content(HttpStatusCode.BadRequest, e.FailureResponse);
            }
            catch (Exception e)
            {
                appLogger.write(e);
                return Content(HttpStatusCode.InternalServerError, "");
            }
        }
    }
}

FinezWebApp452mvc/Controllers/BranchController.cs
using FinezWebApp452mvc.Buisiness;
using FinezWebApp452mvc.Controllers.Base;
using FinezWebApp452mvc.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FinezWebApp452mvc.Controllers
{
    public class BranchController : BaseController
    {
        private BranchManager branchManager { get; set; }
        public BranchController()
        {
            this.branchManager = new BranchManager(this.dbContext);
        }
        // GET: Branch
        public async Task<ActionResult> Index(int Id)
        {
            var branch = await this.branchManager.getBranch(Id);
            if (branch != null)
            {
                return View(branch);
            }
            else
            {
                return View("Error");
            }
        }

        [HttpPut]
        public async Task<ActionResult> Update(EditBranchVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await this.branchManager.UpdateBranch(model);
                    ModelState.Clear();
                    model.IsSuccess = true;
                    model.SuccessMessage = "Branch updated successfully";
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Failed to edit branch. Try again");
            }
            return PartialView("EditBranchPartial", model);
        }

        public async Task<ActionResult> GetDevices(int BranchId)
        {
            return PartialView("DeviceListView", await branchManager.GetDevices(BranchId));
        }

        [HttpPost]
        public void GenerateDeviceKey(int BranchId)
        {
            this.branchManager.GenerateAndSaveDeviceKey(BranchId);
        }

        [HttpPut]
        public void UpdateDeviceStatus(int Id,DeviceStatus Status)
        {
            this.branchManager.UpdateDeviceStatus(Id, (int)Status);
        }
    }
}

FinezWebApp452mvc/Views/Branch/DeviceListView.cshtml
@using FinezWebApp452mvc.Models.ViewModels
@model List<FinezWebApp452mvc.Models.ViewModels.DeviceVM>
@for (int i = 0; i < Model.Count; i++)
{
    <tr >
        <td>@i</td>
        <td>@Model[i].Name</td>
        <td>@Model[i].Id1</td>
        <td>@Model[i].Id2</td>
        <td>@Model[i].Key</td>
        <td>@Model[i].Status</td>
        <td>
            @if (Model[i].Status == DeviceStatus.Active)
            {
                @Ajax.ActionLink("Maintenance", "UpdateDeviceStatus", "Branch", new { Id = Model[i].Id,Status= DeviceStatus.Maintenance }, new AjaxOptions
           {
               HttpMethod = "Put",
               LoadingElementId = "divLoader",
               OnSuccess = "getDevices"
           }, new { @class = "btn btn-primary btn-warning", @style = "margin-right:5px;" })
                
                @Ajax.ActionLink("Block", "UpdateDeviceStatus", "Branch", new { Id = Model[i].Id, Status = DeviceStatus.Blocked }, new AjaxOptions
           {
               HttpMethod = "Put",
               LoadingElementId = "divLoader",
               OnSuccess = "getDevices"
           }, new { @class = "btn btn-primary btn-danger" })
            }
            else if (Model[i].Status != DeviceStatus.UnRegistered)
            {
                @Ajax.ActionLink("Activate", "UpdateDeviceStatus", "Branch", new { Id = Model[i].Id, Status = DeviceStatus.Active }, new AjaxOptions
           {
               HttpMethod = "Put",
               LoadingElementId = "divLoader",
               OnSuccess = "getDevices"
           }, new { @class = "btn btn-primary btn-success" }) 
            }
        </td>
    </tr>
}

FinezWebApp452mvc/Views/Branch/EditBranchPartial.cshtml
@model FinezWebApp452mvc.Models.ViewModels.EditBranchVM
@using (Ajax.BeginForm("Update", "Branch", new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "PUT",
    LoadingElementId = "divLoader",
    UpdateTargetId= "EditBranchFormContainer",
    OnSuccess = "onBranchUpdate"
}))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    if (Model != null && Model.IsSuccess)
    {
        <h4 class="text-success text-center">
            @Model.SuccessMessage
        </h4>
    }
    @Html.HiddenFor(model => model.Id)
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label class="control-label"></label>
                <div class="checkbox">
                    <label>
                        @Html.EditorFor(model => model.IsMainBranch)
                        @Html.LabelFor(model => model.IsMainBranch, htmlAttributes: new { @class = "control-label" })
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
        <div class="row">

            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.Pincode, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Pincode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Pincode, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-default btn-block" />
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary btn-block" />
                </div>
            </div>
        </div>
}

FinezWebApp452mvc/Views/Branch/Index.cshtml
@using FinezWebApp452mvc.Models.ViewModels
@model FinezWebApp452mvc.Models.ViewModels.BranchVM
<div class="row details-view">
    <div class="col-sm-9">
        <div class="details-header">
            <span class="details-title">@(Model.ClientName + " > " + Model.Name)</span> &nbsp&nbsp
            <div>
                <span class="my-badge @(Model.Status==BranchStatus.Active?"badge-green":"badge-red")">@Model.Status</span>
            </div>
        </div>
        <div class="details-content">
            <div class="row">
                <span>
                    <span class="fa fa-map-marker"></span>
                    &nbsp
                    @Model.Street,&nbsp @Model.City,&nbsp @Model.District,&nbsp @Model.State &nbsp PIN : @Model.Pincode
                </span>
                <br />
                <span>
                    <span class="fa fa-phone"></span>
                    &nbsp
                    @Model.Mobile , @Model.Phone
                </span>
                &nbsp&nbsp&nbsp
                <span>
                    <span class="fa fa-envelope "></span>
                    &nbsp
                    @Model.Email
                </span>
                <br />
                <span>
                    <span class="fa fa-calendar"></span>
                    &nbsp Expiry date :
                    @Model.ExpiryDate.ToString("yyyy-MMM-dd")
                </span>
            </div>
            <div>

            </div>
        </div>
    </div>
    <div class="col-sm-1" style="text-align:right">
        <div style="margin:2px;">
            <button class="btn btn-warning" data-toggle="modal" data-target="#EditBranchModal"><span class="fa fa-pencil"></span></button>
        </div>
    </div>
    <div class="col-sm-2" style="text-align:left">
        @if (Model.Status == BranchStatus.Active)
            {
            <div style="margin:2px;">
                <button class="btn btn-danger">Block</button>
            </div>
        }
        else
        {
            <div style="margin:2px;">
                <button class="btn btn-primary">Activate</button>
            </div>
        }

    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default ">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-9">
                        <h3 class="panel-title" style="line-height: 2">Devices</h3>
                    </div>
                    <div class="col-md-3">
                        @Ajax.ActionLink("Generate Key", "GenerateDeviceKey", "Branch", new { BranchId = Model.BranchId }, new AjaxOptions
                       {
                           HttpMethod = "Post",
                           LoadingElementId = "divLoader",
                           OnSuccess = "getDevices"
                       }, new { @class = "btn btn-primary btn-block" })
                    </div>
                    @using (Ajax.BeginForm("GetDevices", "Branch", new AjaxOptions
                    {
                        InsertionMode = InsertionMode.Replace,
                        HttpMethod = "GET",
                        LoadingElementId = "divLoader",
                        UpdateTargetId = "DeviceListContainer",
                    }, new { id = "formGetDevices" }))
                    {
                        @Html.Hidden("BranchId", Model.BranchId);
                    }
                </div>
            </div>
            <div class="panel-body height-50">
                <table class="table table-striped table-hover my-table">
                    <thead>
                        <tr>
                            <th class="">#</th>
                            <th class="">Name</th>
                            <th class="">ID1</th>
                            <th class="">ID2</th>
                            <th class="">Key</th>
                            <th class="">Status</th>
                            <th class="col-md-3">Action</th>
                        </tr>
                    </thead>
                    <tbody id="DeviceListContainer"></tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default ">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-9">
                        <h3 class="panel-title" style="line-height: 2">Employees</h3>
                    </div>
                </div>
            </div>
            <div class="panel-body height-50">
                <table class="table table-striped table-hover my-table">
                    <thead>
                        <tr>
                            <th class="">Name</th>
                            <th class="">Contacts</th>
                            <th class="">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (EmployeeVM emp in Model.Employees)
                        {
                            <tr>
                                <td class="">@emp.Name</td>
                                <td class="">
                                    @emp.Phone,<br/>
                                    @emp.Mobile,<br/>
                                    @emp.Email
                                </td>
                                <td class="">@emp.Status</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<div class="modal fade" id="EditBranchModal" tabindex="-1" role="dialog" aria-labelledby="Edit Branch">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title" id="myModalLabel">Edit Branch</h3>
                </div>
                <div class="modal-body" id="EditBranchFormContainer">
                    @Html.Partial("EditBranchPartial", AutoMapper.Mapper.Map<EditBranchVM>(Model))
                </div>
            </div>
        </div>
    </div>
@section scripts{
    <script type="text/javascript">
        $(function () {
            getDevices();
        })
        function getDevices() {
            $("#formGetDevices").submit();
        }
        function onBranchUpdate(data) {
            if (data.indexOf("field-validation-error") > -1) return;
            else location.reload(true);
        }
    </script>
}