FinezWebApp452mvc/Controllers/ClientController.cs
using AutoMapper;
using FinezWebApp452mvc.Buisiness;
using FinezWebApp452mvc.Controllers.Base;
using FinezWebApp452mvc.Models;
using FinezWebApp452mvc.Models.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FinezWebApp452mvc.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ClientController : BaseController
    {
        private ClientManager clientManager { get; set; }
        private BranchManager branchManager { get; set; }
        public ClientController()
        {
            this.clientManager = new ClientManager(this.dbContext);
            this.branchManager = new BranchManager(this.dbContext);
        }
        // GET: Client
        public async Task<ActionResult> Index()
        {
            return View(await this.clientManager.getClients(new SearchClientVM()));
        }

        [HttpGet]
        public async Task<ActionResult> GetClients(SearchClientVM model)
        {
            return PartialView("ClientListPartial", await this.clientManager.getClients(model));
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(AddClientViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    clientManager.addClient(model);
                    model = new AddClientViewModel();
                    model.IsAdded = true;
                    model.SuccessMessage = "Client added successfully";
                    ModelState.Clear();

                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Failed to add client. Try again");
            }

            return PartialView("AddPartial", model);
        }

        public async Task<ActionResult> Details(int Id)
        {
            var client = await this.clientManager.getClient(Id);
            if (client != null)
                return View(client);
            else
                return View("Error");

        }

        [HttpPost]
        public async Task<ActionResult> AddBranchAndAdmin(AddBranchVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model = await branchManager.AddBranchAndAdmin(model,HttpContext.GetOwinContext());
                    if(model.IsSuccess)
                        ModelState.Clear();
                    else
                        ModelState.AddModelError("", "Failed to add branch. Try again");
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Failed to add branch. Try again");
            }

            return PartialView("AddBranchPartial", model);
        }

        [HttpGet]
        public async Task<ActionResult> GetBranches(int clientId,string SearchText)
        {
            return PartialView("BranchList",await this.branchManager.GetBranches(clientId, SearchText));
        }
    }
}

FinezWebApp452mvc/Views/Shared/PaginationView.cshtml
@model FinezWebApp452mvc.Models.ViewModels.PaginationModel
@{
    int totalPages = Model.RowCount / Model.PerPage;
}
@if (totalPages > 1)
{
    <nav class="pagination-container pull-right" style="" aria-label="Page navigation">
        <ul class="pagination">
            @if (Model.CurrentPage != 1)
            {
                <li class=""><a class="" href="javascript:void(0);" aria-label="Previous" onclick="@(Model.OnClickfunction)(1)"><span aria-hidden="true">«</span></a></li>
            }
            else
            {
                <li class="disabled"><a class="" href="javascript:void(0);" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
            }
            @for (var i = Model.CurrentPage - 2; i < Model.CurrentPage; i++)
            {
                if (i > 0)
                {
                    <li class=""><a class="" href="javascript:void(0);" onclick="@(Model.OnClickfunction)(@i)">@i</a></li>
                }
            }
            <li class="active">
                <a class="">@Model.CurrentPage </a>
                @for (var i = Model.CurrentPage + 1; i < Model.CurrentPage + 3 && i <= totalPages; i++)
                {
                <li class=""><a class="" href="javascript:void(0);" onclick="@(Model.OnClickfunction)(@i)">@i</a></li>
                }
                @if (Model.CurrentPage != totalPages)
                {
                    <li class=""><a class="" href="javascript:void(0);" aria-label="Next" onclick="@(Model.OnClickfunction)(@totalPages)"><span aria-hidden="true">»</span></a></li>
                }
                else
                {
                    <li class="disabled"><a class="" href="javascript:void(0);" aria-label="Next" onclick="@(Model.OnClickfunction)(@totalPages)"><span aria-hidden="true">»</span></a></li>
                }
            </ul>
        </nav>
}

FinezWebApp452mvc/Views/Shared/_BlankLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="@ViewBag.bodyClass">
    <div class="wrapper">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FinezWebApp452mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="wrapper">
        <div id="divLoader" style="" class="loader-overlay">
            <div class="loader loader-lg loader-blue"></div>
        </div>
        <div class="sidebar navbar-default ">
            <div class="user-block hidden-xs">
                <img src="~/images/user.png" alt="">
                <div class="user-content sidebar-sm-hidden-child">
                    <h5>Admin</h5><br />
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <button type="submit" style="padding:0px;font-size:12px" class="btn btn-link">Logout</button>
                    }
                </div>
            </div>

            <div class="clearfix"></div>
            <div class="navbar-collapse collapse">
                <ul class="nav parent-menu">
                    <li>
                        <a class="active" href="index.html">
                            <i class="fa fa-home"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="">
                        <a>
                            <i class="fa fa-users"></i>
                            <span>Clients</span>
                        </a>
                        <ul class="nav child-menu">
                            <li><a href="@Url.Action("Index", "Client")"><span>All clients</span></a></li>
                            <li><a href="@Url.Action("Add", "Client")">Add client</a></li>
                        </ul>
                    </li>
                    @*<li>
                        <a href="beneficiary_requests.html">
                            <i class="fa fa-handshake-o"></i>
                            <span>Beneficiary requests</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="fa fa-exchange"></i>
                            <span>Transactions</span>
                        </a>
                        <ul class="nav child-menu">
                            <li><a href="transactions.html">All</a></li>
                            <li><a href="transactions_completed.html">Completed</a></li>
                            <li><a href="transactions_pending.html">Pending</a></li>
                            <li><a href="transactions_failed.html">Failed</a></li>
                        </ul>
                    </li>
                    <li>
                        <a class="">
                            <i class="fa fa-user-circle "></i>
                            <span>Admin users</span>
                        </a>
                        <ul class="nav child-menu">
                            <li><a href="admin_users.html" class="">All users</a></li>
                            <li><a href="add_adminUser.html">Add user</a></li>
                            <li><a href="admin_type.html">User types</a></li>
                            <li><a href="Blocked_admin.html">Blocked users</a></li>
                        </ul>
                    </li>*@

                </ul>
            </div>
            <div class="brand-icon  hidden-xs">
                <img src="images/logo.png" alt="">
            </div>
        </div>
        <div class="content-wrapper">
            <nav class="navbar navbar-default navbar-static-top ">
                <div class="navbar-header header">
                    <button type="button" class="navbar-toggle pull-left" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <button type="button" class="navbar-toggle side-bar-toggle pull-left" data-target=".sidebar">
                        <span class="sr-only">Toggle</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">
                        @ViewBag.Title
                    </div>
                </div>

            </nav>
            <div class="container-fluid" style="padding:0px 15px;">
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>